#!/usr/bin/env bash

python -m venv venv
source venv/bin/activate
python -m pip install --upgrade pip setuptools wheel
pip install awsebcli

# see https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb3-init.html
application_name=${PWD##*/}
platform=node.js
region=ap-southeast-1

eb init "$application_name" --platform "$platform" --region "$region"